### ISSUE TITLE
Add support for serving rendered Markdown files (.md)

### ISSUE THREAD

**Issue by CurtisLusmore** [CurtisLusmore/ghp#1]
GitHub Pages will render Markdown files (`.md`) as HTML before serving them, so it'd be great to add support for that to make this more feature-complete.

**Comment by arjunmahishi** [comment]
I am working on this.. I'll probably make a PR by today

**Comment by CurtisLusmore** [comment]
Oh awesome, good luck! For the record I was thinking of just hitting [api.github.com/markdown](https://developer.github.com/v3/markdown/#render-an-arbitrary-markdown-document) to do this, to avoid pulling in more dependencies, but I'm sure there's a million ways to render markdown as HTML.

**Comment by arjunmahishi** [comment]
> Oh awesome, good luck! For the record I was thinking of just hitting [api.github.com/markdown](https://developer.github.com/v3/markdown/#render-an-arbitrary-markdown-document) to do this, to avoid pulling in more dependencies, but I'm sure there's a million ways to render markdown as HTML.

Oh... I was going to use `blackfriday`. But I guess its best if we avoid adding dependencies.
