### ISSUE TITLE
Add missing prerequisites

### ISSUE THREAD

**Issue by makbol** [CurtisLusmore/ghp#2]
There isn't mention I need to have installed Go already

**Comment by CurtisLusmore** [comment]
Thanks for raising this, good point. I'll do up a release as well with pre-compiled binaries, for those who don't have/want Go.

**Comment by CurtisLusmore** [comment]
Added a section to the Readme for installation instructions, and also added pre-compiled binaries to the [latest Release](https://github.com/CurtisLusmore/ghp/releases). Thanks.

**Comment by makbol** [comment]
Thanks for reacting. I meant to simply add e.g  _you need to have installed Go_ or even better for Mac ppl _install Go via homebrew_. I think keeping binaries in repo might cause more trouble then it's worth.

Anyways it's up to you 😊. Keep it up! Good work 👍

**Comment by CurtisLusmore** [comment]
Thanks! For the record, the binaries aren't in the repo, they're just attached to the release.
